full_team_to_abbrev = {
    "Atlanta Falcons": "ATL",
    "Buffalo Bills": "BUF",
    "Chicago Bears": "CHI",
    "Cincinatti Bengals": "CIN" ,
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL" ,
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GRB",
    "Tennesse Titans": "TEN",
    "Indianapolis Colts": "IND" ,
    "Kansas City Chiefs": "KAC",
    "Las Vegas Raiders": "LAV",
    "Los Angeles Rams": "LAR",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NEE",
    "New Orleans Saints": "NEO",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Arizona Cardinals": "ARI",
    "Pittsburgh Steelers": "PIT",
    "Los Angeles Chargers": "LAC",
    "San Francisco 49ers": "SAF",
    "Seattle Seahawks": "SEA",
    "Tampa Bay Buccaneers": "TAB",
    "Washington Commanders": "WSH", 
    "Carolina Panthers": "CAR",
    "Jacksonville Jaguars": "JAX",
    "Baltimore Ravens": "BAL",
    "Houston Texans": "HOU"
}