abbreviation_full_team_dict = {
    "ATL": ["Atlanta Falcons"], 
    "BUF": ["Buffalo Bills"], 
    "CHI": ["Chicago Bears"], 
    "CIN": ["Cincinatti Bengals"], 
    "CLE": ["Cleveland Browns"], 
    "DAL": ["Dallas Cowboys"], 
    "DEN": ["Denver Broncos"], 
    "GRB": ["Green Bay Packers"],
    "TEN": ["Tennessee Titans"], 
    "IND": ["Indianapolis Colts"], 
    "KAC": ["Kansas City Chiefs"],
    "LAV": ["Las Vegas Raiders", "Oakland Raiders"],
    "LAR": ["Los Angeles Rams", "St. Louis Rams"], 
    "MIA": ["Miami Dolphins"], 
    "MIN": ["Minnesota Vikings"], 
    "NEE": ["New England Patriots"],
    "NEO": ["New Orleans Saints"],
    "NYG": ["New York Giants"], 
    "NYJ": ["New York Jets"], 
    "PHI": ["Philadelphia Eagles"], 
    "ARI": ["Arizona Cardinals"], 
    "PIT": ["Pittsburgh Steelers"] 
    "LAC": ["Los Angeles Chargers", "San Diego Chargers"],
    "SAF": ["San Francisco 49ers"],
    "SEA": ["Seattle Seahawks"], 
    "TAB": ["Tampa Bay Buccaneers"],
    "WSH": ["Washington Commanders", "Washingon Football Team", "Washington Redskins"],
    "CAR": ["Carolina Panthers"], 
    "JAX": ["Jacksonville Jaguars"], 
    "BAL": ["Baltimore Ravens"], 
    "HOU" : ["Houston Texans"] 
}